fix `DocTestFilters = nothing` in at-meta
Using 
````
```@meta
DocTestFilters = nothing
```
````
as [suggested in the docs](https://juliadocs.github.io/Documenter.jl/stable/man/doctests/#Filtering-Doctests), I get
```
ERROR: LoadError: MethodError: no method matching occursin(::Nothing, ::SubString{String})
Closest candidates are:
  occursin(::Union{AbstractChar, AbstractString}, ::AbstractString) at strings/search.jl:622
  occursin(::Regex, ::SubString; offset) at regex.jl:269
  occursin(::Regex, ::AbstractString; offset) at regex.jl:264
```
To me, it looks like this is the reason for this behavior.